# --- EIGENE SHORTCUT-KORREKTUREN ---

# 1. Aktives Fenster auf Desktop [1-10] verschieben und dorthin wechseln
bind = ALT SHIFT, 1, movetoworkspace, 1
bind = ALT SHIFT, 2, movetoworkspace, 2
bind = ALT SHIFT, 3, movetoworkspace, 3
bind = ALT SHIFT, 4, movetoworkspace, 4
bind = ALT SHIFT, 5, movetoworkspace, 5
bind = ALT SHIFT, 6, movetoworkspace, 6
bind = ALT SHIFT, 7, movetoworkspace, 7
bind = ALT SHIFT, 8, movetoworkspace, 8
bind = ALT SHIFT, 9, movetoworkspace, 9
bind = ALT SHIFT, 0, movetoworkspace, 10

# 2. Fix: Aktives Fenster und alle Instanzen (selbe PID) schließen
bind = ALT SHIFT, Q, exec, hyprctl activewindow | grep pid | tr -d ' \tpid:' | xargs kill
